// <auto-generated />
using System;
using ConsultoriaDevApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsultoriaDevApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("ConsultoriaDevApp.Models.Servico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Preco")
                        .HasColumnType("TEXT");

                    b.Property<string>("TempoResposta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Servicos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Descricao = "Revisão e planejamento da arquitetura do seu sistema.",
                            Nome = "Consultoria de Arquitetura",
                            Preco = 500m,
                            TempoResposta = "48h"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Descricao = "Análise completa do código com relatório de melhorias.",
                            Nome = "Code Review",
                            Preco = 250m,
                            TempoResposta = "24h"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            Descricao = "Implementação de funcionalidade sob demanda.",
                            Nome = "Desenvolvimento de Feature",
                            Preco = 800m,
                            TempoResposta = "72h"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            Descricao = "Diagnóstico e correção de bugs em produção.",
                            Nome = "Correção de Bug Crítico",
                            Preco = 350m,
                            TempoResposta = "12h"
                        });
                });

            modelBuilder.Entity("ConsultoriaDevApp.Models.Solicitacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AtualizadaEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DevId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailCliente")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ServicoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DevId");

                    b.HasIndex("ServicoId");

                    b.ToTable("Solicitacoes");
                });

            modelBuilder.Entity("ConsultoriaDevApp.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ConsultoriaDevApp.Models.Solicitacao", b =>
                {
                    b.HasOne("ConsultoriaDevApp.Models.Usuario", "Dev")
                        .WithMany()
                        .HasForeignKey("DevId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ConsultoriaDevApp.Models.Servico", "Servico")
                        .WithMany("Solicitacoes")
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dev");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("ConsultoriaDevApp.Models.Servico", b =>
                {
                    b.Navigation("Solicitacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
